### ISSUE TITLE
How to use only the extracted image

### ISSUE THREAD

**Issue by HazemAbdullah** [card-io/card.io-iOS-SDK#102]
Hello, I have a UIImage that is already contain the extracted card (I'm not using camera view), how can I call the sdk in this way?

**Comment by dgoldman-ebay** [comment]
@HazemAbdullah unfortunately, no, that will not work. card.io actually works from a *video* of the card, rather than a single image. And it depends on the camera's resolution and image size.

**Comment by HazemAbdullah** [comment]
Is it easy to modify it to accept the image not video?

**Comment by dgoldman-ebay** [comment]
No, I'm afraid not. For one thing, the library requires multiple slightly different images in order to be confident in its results.
