### ISSUE TITLE
Change the title of CardIOPaymentViewController in iOS. 

### ISSUE THREAD

**Issue by vijayviswas** [card-io/card.io-iOS-SDK#103]
Can we change the title of CardIOPaymentViewController in iOS? As of now CardIOPaymentViewController title is "Card". Is it configurable?

**Comment by dgoldman-ebay** [comment]
@vijayviswas no, very little of the textual content in card.io can be changed by the integrating app.

However, the source code for card.io is available [here](https://github.com/card-io/card.io-iOS-source). If you download that codebase and build your own copy of the card.io SDK, modifying that title will be quite straightforward.
