### ISSUE TITLE
Users can type more than 2 digits in the card expiration field

### ISSUE THREAD

**Issue by codeman9** [card-io/card.io-iOS-SDK#104]
If the user types in an invalid expiration year (one that is in the past, say "11") then they will be able to enter 4 digits into the field.

**Comment by dgoldman-ebay** [comment]
Thanks, @codeman9.

The original intention was to allow users to enter either a 2-digit year (`16`) or a 4-digit year (`2016`). But the expiration-date-checking code has been modified here and there over time, and now needs a bit of tidying up.

**Comment by dgoldman-ebay** [comment]
Fixed in [version 5.0.4](https://github.com/card-io/card.io-iOS-SDK/releases).

Thanks again, @codeman9, for bringing this to our attention.
