### ISSUE TITLE
Card-io sdk: Application restart after camera access changed in device setting

### ISSUE THREAD

**Issue by vijayviswas** [card-io/card.io-iOS-SDK#105]
Application restart after camera access changed in device setting. Is it officially documented anywhere in apple document?

**Comment by dgoldman-ebay** [comment]
@vijayviswas yes, I have noticed this as well. See my comments [here](https://github.com/card-io/card.io-iOS-source/commit/ceb248ff13aebcf630a9107096c8e3480b659eb6#diff-154a40f8fd2bfeef862c5194b986c9e5R81) at lines 80 and 81.

IIRC, I found some comments in Apple documentation that could be interpreted as hinting at this behavior, but I did not find any explicit documentation of the fact.

**Comment by vijayviswas** [comment]
Thanks @dgoldman-ebay.
