### ISSUE TITLE
Card IO : Set Focus Mode for Non-payment cards

### ISSUE THREAD

**Issue by biksappdev** [card-io/card.io-iOS-SDK#106]
Hi @dgoldman-ebay , I have been trying to get this going with little luck. So I tried calling the autoFocusOnce as below - 

- (void)startVideoStreamSession {
  [self.videoStream startSession];
  [self.videoStream autofocusOnce];
  // If we don't do this, then when the torch was on, and the card read failed,
  // it still shows as on when this view is re-displayed, even though the ending
  // of the session turned it off.
  [self updateLightButtonState];
}

Also, //      if (!self.currentlyAdjustingFocus && frame.focusSucks && [self hasAutofocus]) {
        NSTimeInterval now = [[NSDate date] timeIntervalSince1970];
//        if (now - self.lastAutoFocusOnceTime > kMinTimeIntervalForAutoFocusOnce) {
          self.lastAutoFocusOnceTime = now;
          CardIOLog(@"Auto-triggered focusing");
          [self autofocusOnce];
          [self performSelector:@selector(resumeContinuousAutofocusing) withObject:nil afterDelay:0.1f];
          didAutoFocus = YES;
//        }
//      }

Removed the condition for triggering autoFocusOnce method while capturing a picture, however I am not able to get a clear shot every time. The library captures an image before it recognizes the corners.
Kindly put me in the right direction to resolve this.
I am looking forward to get the same behavior as it is for payment cards.

![img_0226](https://cloud.githubusercontent.com/assets/9661978/7211408/4701fd0c-e50f-11e4-8268-5be5b52c9e35.PNG)

**Comment by dgoldman-ebay** [comment]
Issue moved to [card.io-iOS-source](https://github.com/card-io/card.io-iOS-source/issues/21)
