### ISSUE TITLE
iOS : Card IO Crashes when app is sent to background 

### ISSUE THREAD

**Issue by biksappdev** [card-io/card.io-iOS-SDK#107]
@dgoldman-ebay , I am running into a scenario where my app crashes when I sent it to the background and open again, while it is on the card capture screen. Below is the crash log, do I need to do any additional handling of closing the session in my VC when app goes to background ?

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Multiple audio/video AVCaptureInputs are not currently supported.'

Kindly assist.

**Comment by dgoldman-ebay** [comment]
@biksappdev are you using our card.io SDK as-is, or are you making your own video calls (as you've discussed in other issues)?

**Comment by biksappdev** [comment]
@dgoldman-ebay , I have Card IO integrated through Cocoa Pods in my app.

**Comment by biksappdev** [comment]
@dgoldman-ebay , I believe the crash was introduced after updating to the latest version, as below - 
       pod 'CardIO', '~> 5.0'
Is there something that changed from previous versions that might cause it ?

**Comment by dgoldman-ebay** [comment]
@biksappdev thanks. I'm trying to reproduce this crash, so far without success.

Here is what I'm trying:

1. Launch app that includes card.io
2. Navigate to the card-scanning screen.
3. Tap the iPhone's Home button to background the app.
4. Optionally, launch another app or two.
5. Double-tap the Home button and select the original app.
=> For me, the app comes back up with the card-scanning screen operational. No crash.

Are you following different steps?

**Comment by biksappdev** [comment]
@dgoldman-ebay , yes app crashes for me with the same steps.

**Comment by dgoldman-ebay** [comment]
@biksappdev I don't know why your app crashes while the 3 apps I've tried do not.

If you can't find a reason for the crash, would it be possible for you to share your project with me (with full confidentiality, of course), so that I can try building and debugging it?

**Comment by biksappdev** [comment]
![screen shot 2015-04-28 at 3 10 07 pm](https://cloud.githubusercontent.com/assets/9661978/7381601/e8155614-edb9-11e4-91ac-dc9e94a2b227.png)

**Comment by biksappdev** [comment]
@dgoldman-ebay , this is the crash trace and it happens the moment I launch the app from background.

**Comment by dgoldman-ebay** [comment]
@biksappdev would it be possible for you to share your project with me (with full confidentiality, of course), so that I can try building and debugging it?

**Comment by biksappdev** [comment]
@dgoldman-ebay , I am sorry I cannot do that right now due to security policies, though I wish I could.

**Comment by dgoldman-ebay** [comment]
@biksappdev understood. Too bad. :(

What happens for you if you build and run the Sample App from the repo? Does it also crash for you?

**Comment by biksappdev** [comment]
@dgoldman-ebay , I tried and it doesn't happen. Leaves me wondering what can go wrong in my app which might cause this. I rolled back to an older version of Card IO Library, and still this happens with my current app, so may be its something else but the crash is being triggered in the CardIO. I'm clueless.

**Comment by dgoldman-ebay** [comment]
@biksappdev does your app include any of the changes we were discussing in https://github.com/card-io/card.io-iOS-SDK/issues/100 ? Or any other code related to the camera or video session?

**Comment by biksappdev** [comment]
@dgoldman-ebay , so I tracked the issue to the cause, in my app I have to use this in one of the delegate methods in AppDelegate.m class, this very line is triggering the crash in Card IO.

    [[NSNotificationCenter defaultCenter] postNotificationName:UIApplicationDidBecomeActiveNotification object:nil];

this is added at last inside the '- (void)applicationWillEnterForeground:(UIApplication *)application' method.
Could you please help in understanding why this would trigger the crash ?

**Comment by dgoldman-ebay** [comment]
@biksappdev your code should not post `UIApplicationDidBecomeActiveNotification`. That notification is automatically posted by iOS when the app is made active. It is incorrect for you to post the same notification an additional time.

card.io is watching for that notification to know when the app has been restored from the background. Upon receiving the notification, card.io restarts its camera session. (card.io had stopped its camera session when the app had previously been sent to the background). When your app sends the same notification a second time, card.io therefore tries to start a second camera session, which is not allowed.
