### ISSUE TITLE
Doesn't allow user to enter expiry date year more than 15 years from now?

### ISSUE THREAD

**Issue by vijayviswas** [card-io/card.io-iOS-SDK#108]
Hi,

Expiry date year is displayed in red when I enter expiry date year as "2099". I think allows 15 years from now. why?

**Comment by dgoldman-ebay** [comment]
@vijayviswas we included a 15-year cutoff as a sanity-check for the user, to catch typing mistakes.

Have you encountered cards with expiration dates beyond 15 years in the future?

**Comment by vijayviswas** [comment]
@dgoldman-ebay I haven't seen any card with expiration date beyond 15 years. Testers have asked this question and I passed it to forum. Do we need to restrict to 15 years? its a question to all who are using card-io sdk.

**Comment by josharian** [comment]
As soon as there's a use case in which anything past 15 years makes any sense, then by all means we will open it up. I don't know of any such use case. If you have one, please re-open and let us know.
