### ISSUE TITLE
Will userDidProvideCreditCardInfo method returns nil CardIOCreditCardInfo object?

### ISSUE THREAD

**Issue by vijayviswas** [card-io/card.io-iOS-SDK#109]
Hi,

Will below delegate method returns nil CardIOCreditCardInfo object?
- (void)userDidProvideCreditCardInfo:(CardIOCreditCardInfo *)cardInfo inPaymentViewController:(CardIOPaymentViewController *)paymentViewController;

I haven't encountered any scenarios.

**Comment by dgoldman-ebay** [comment]
@vijayviswas that delegate method is called only after a successful scan. `cardInfo` will never be `nil`.
