### ISSUE TITLE
Crashes when user taps "Cancel" and "Enter Manually" buttons simultaneously

### ISSUE THREAD

**Issue by arun-kumar0105** [card-io/card.io-iOS-SDK#112]
Tap simultaneously on "Cancel" and "Enter Manually" buttons.

**Comment by dgoldman-ebay** [comment]
@arun-kumar0105 I've tried several times to reproduce this, on a few phones, without success. But just now I succeeded in generating a crash, just one time.

Do you have any tips for reliably tapping both buttons simultaneously enough to cause the crash?

**Comment by arun-kumar0105** [comment]
@dgoldman-ebay Please tap both buttons at a time,immediately it crashes.I tried it 5-6 time and it crashed every-time.

**Comment by dgoldman-ebay** [comment]
Fixed in [version 5.0.6](https://github.com/card-io/card.io-iOS-SDK/releases).

Thanks @arun-kumar0105 !

**Comment by arun-kumar0105** [comment]
@dgoldman-ebay  Thank you very much.
