### ISSUE TITLE
Scan view doesn't support iPhone 5 screen size

### ISSUE THREAD

**Issue by tonyli508** [card-io/card.io-iOS-SDK#116]
It seems scan card camera view is only support iPhone 4 size, there are black spaces both on top and bottom of the screen.

**Comment by dgoldman-ebay** [comment]
@tonyli508 we use the standard 640×480 camera resolution on all devices.

For devices with a taller aspect ratio than 640x480, this implies that we must either add black space above and below the camera image, or else that we enlarge the camera image and cut off its sides. We have chosen the former approach.
