### ISSUE TITLE
Crash when using Card IO on iOS 9 beta

### ISSUE THREAD

**Issue by ngthanhtan91** [card-io/card.io-iOS-SDK#121]
I'm getting crash reports when opening the CardIOView on iOS 9 beta on simulator. I have no device run on iOS 9 beta now. My version is 5.0.6

*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 12} out of bounds; string length 9'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fae7ca5 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010f0f7dcd objc_exception_throw + 48
	2   CoreFoundation                      0x000000010fae7bdd +[NSException raise:format:] + 205
	3   CoreFoundation                      0x000000010fad383a -[NSTaggedPointerString getCharacters:range:] + 394
	4   CoreFoundation                      0x000000010f9bef7a CFStringCompareWithOptionsAndLocale + 2970
	5   CoreFoundation                      0x000000010fad418b -[NSTaggedPointerString compare:options:range:locale:] + 219
	6   Foundation                          0x000000010f539027 -[NSString compare:options:range:] + 29
	7   BevNow                              0x000000010b6c7169 __52-[CardIOLocalizer localizeString:adaptedForCountry:]_block_invoke + 60
	8   CoreFoundation                      0x000000010fa1584b -[NSArray indexOfObject:inSortedRange:options:usingComparator:] + 491
	9   BevNow                              0x000000010b6c6eac -[CardIOLocalizer localizeString:adaptedForCountry:] + 473
	10  BevNow                              0x000000010b6c7a23 CardIOLocalizedStringWithAlert + 1305
	11  BevNow                              0x000000010b6c7bbe CardIOLocalizedString + 56
	12  BevNow                              0x000000010b6b2254 -[CardIODataEntryViewController viewDidLoad] + 258
	13  UIKit                               0x000000010deaf3f6 -[UIViewController loadViewIfRequired] + 871
	14  UIKit                               0x000000010deaf765 -[UIViewController view] + 27
	15  UIKit                               0x000000010defc6ba -[UINavigationController preferredContentSize] + 194
	16  UIKit                               0x000000010de875ed -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 152
	17  UIKit                               0x000000010de83c3f __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 95
	18  UIKit                               0x000000010dd38907 _runAfterCACommitDeferredBlocks + 317
	19  UIKit                               0x000000010dd4a091 _cleanUpAfterCAFlushAndRunDeferredBlocks + 95
	20  UIKit                               0x000000010dd5593c _afterCACommitHandler + 90
	21  CoreFoundation                      0x000000010fa120b7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	22  CoreFoundation                      0x000000010fa12027 __CFRunLoopDoObservers + 391
	23  CoreFoundation                      0x000000010fa07b5b __CFRunLoopRun + 1147
	24  CoreFoundation                      0x000000010fa07458 CFRunLoopRunSpecific + 488
	25  GraphicsServices                    0x0000000111048bca GraphicsServices + 52170
	26  UIKit                               0x000000010dd2d1c2 UIApplicationMain + 171
	27  BevNow                              0x000000010b698b7f main + 111
	28  libdyld.dylib                       0x000000010ffd392d libdyld.dylib + 10541
	29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dgoldman-ebay** [comment]
Thanks for the report. Please see https://github.com/card-io/card.io-iOS-SDK/issues/120
