### ISSUE TITLE
IOS 9 Beta 3 Crash

### ISSUE THREAD

**Issue by ersun** [card-io/card.io-iOS-SDK#125]
Hey, i use cardio with paypal sdk v5.0.6 , but iOS 9 beta 3 not work , can you see the crash error, 
can you help me to figure out that? 
Thanks

*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 7} out of bounds; string length 6'
*** First throw call stack:
(0x182237f94 0x196bdbf2c 0x182237edc 0x18221f520 0x1821290e4 0x18221fccc 0x10050a0b4 0x1821700c8 0x100509e00 0x10050a9e0 0x10050ab88 0x1004de4ac 0x18784a90c 0x18784a630 0x187bcf3ec 0x187b919cc 0x187b8e654 0x187af3d30 0x187affa44 0x18783cf08 0x1821eef44 0x1821eccbc 0x1821ed0ec 0x182119800 0x18d1a7170 0x1878b25e8 0x10010a4a4 0x1974168b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
###### Modanisa`__52-[CardIOLocalizer localizeString:adaptedForCountry:]_block_invoke:

**Comment by dgoldman-ebay** [comment]
@ersun we have fixed this crash in the [latest release of card.io](https://github.com/card-io/card.io-iOS-SDK/releases), version 5.1.0.

The PayPal-iOS-SDK has not yet had a chance to be updated to incorporate this new version of card.io. An update will be coming fairly soon; you can check the [PayPal-iOS-SDK repo](https://github.com/paypal/PayPal-iOS-SDK/releases) to keep track.

**Comment by ersun** [comment]
Thanks a lot for your quick answer
