### ISSUE TITLE
Can we extract user name using card.io from debit or credit card

### ISSUE THREAD

**Issue by Daemon-Devarshi** [card-io/card.io-iOS-SDK#127]
I am trying to identify if we can extract user name using card.io from debit or credit card by looking at CardIOCreditCardInfo.h file at this link: https://github.com/card-io/card.io-iOS-SDK/blob/master/CardIO/CardIOCreditCardInfo.h, seems like currently it does not support its extraction, please confirm.

**Comment by josharian** [comment]
Correct; card.io does not read the name (yet).
