### ISSUE TITLE
Isuue with scanning cards

### ISSUE THREAD

**Issue by jarvisdeveloper** [card-io/card.io-iOS-SDK#128]
Hi, 
     i scanned 2 to 3 different axis bank cards it scanning perfectly, some cards are not scanning mostly like cards with silver tags, please give me some solution for this.

Thanks & regards,
Gopi.

**Comment by josharian** [comment]
There is no quick fix, and certainly no fix I can make without having access to the cards. However, if you feel inspired, you could grab the source and try to figure out what stage of the pipeline the scanning is failing at.
