### ISSUE TITLE
Option to disable copy/paste in CC UITextField

### ISSUE THREAD

**Issue by cnowacek** [card-io/card.io-iOS-SDK#132]
It would be helpful from a security standpoint to disallow copy/paste on the credit card text field. Since Card.io uses the general pasteboard any copy/pasted data coming from the text field can be accessible from other apps.

**Comment by josharian** [comment]
Disallowing copy/paste effectively disallows 1password; I'd rather support password managers than try to keep the pasteboard clean. And by the time the user discovers that pasting is disabled, their password is probably already on the pasteboard--we'd just be shutting the proverbial barn door.
