### ISSUE TITLE
ViewController never finishes

### ISSUE THREAD

**Issue by pbahuk** [card-io/card.io-iOS-SDK#135]
The card scans and after filling the details that are not scanned automatically, the done button never works. Please help.

**Comment by dgoldman-ebay** [comment]
@pbahuk there might be something "wrong" (according to card.io's logic) with the information inside one of the fields. If you don't see any problems, could you provide a screenshot?

**Comment by pbahuk** [comment]
Even though i have filled all the details, the done button is not working.

**Comment by dgoldman-ebay** [comment]
@pbahuk Please provide a screenshot.

**Comment by pbahuk** [comment]
PFA attached an image. Even when the card is read, and the remaining
details filled. The done button does not work.

**Comment by pbahuk** [comment]
sorry ,my bad. I included every other file than the main CardIO.h file.

**Comment by dgoldman-ebay** [comment]
Glad you figured it out, @pbahuk. :smile_cat:
