### ISSUE TITLE
fees for card.io credit card scanning? 

### ISSUE THREAD

**Issue by rasamad** [card-io/card.io-iOS-SDK#136]
when using the card.io credit card scanning, are there any extra charges?

**Comment by sabhiram** [comment]
card.io is an open source library / framework to ocr a credit card into some text. It has nothing to do with payment processing or charges in general.

**Comment by dgoldman-ebay** [comment]
Thanks, @sabhiram! @rasamad there are no charges associated with using card.io itself.
