### ISSUE TITLE
How can I make the CardIOView fill up the whole screen?

### ISSUE THREAD

**Issue by jlubeck** [card-io/card.io-iOS-SDK#138]
I'm using the whole view.frame to init the view but it's still not filling it totally. I see empty space both at the top and bottom

> ![Image of CardIOView](https://lh4.googleusercontent.com/-Xjq-jQpZRn8/VeXq4f2ffYI/AAAAAAAABe0/ss7FK5Jm2l8/w330-h585-no/2015-09-01.jpg)

I even tried adding it in the viewDidAppear, to make sure no autolayout constraints were not yet completed, but still the same.

```swift
	override func viewDidAppear(animated: Bool) {
		let cardIOView = CardIOView(frame: view.frame)
		cardIOView.delegate = self
		self.view.addSubview(cardIOView)
	}
```

Thanks

**Comment by dgoldman-ebay** [comment]
Please see #116
