### ISSUE TITLE
Returned expiration date/month (manual entry) is wrong on 5.1.0 and 5.1.1

### ISSUE THREAD

**Issue by ldiqual** [card-io/card.io-iOS-SDK#140]
Entered this:

![](https://www.dropbox.com/s/3im2doci7bhgtii/Screenshot%202015-09-19%2000.20.26.png?raw=1)

got this:

![](https://www.dropbox.com/s/p5ni3q7wga34669/Screenshot%202015-09-19%2000.19.05.png?raw=1)

Affected versions: 5.1.0, 5.1.1. Can't revert to 5.0.6 because of the iOS 9 crash :(

**Comment by dgoldman-ebay** [comment]
@ldiqual the entry field says "MM/YY", not "DD/MM" or "MM/DD".

In other words, everything is working correctly. card.io works with `month/year`, not `day/month`.

**Comment by ldiqual** [comment]
Absolutely, I don't know what I was thinking. Sorry for the noise!

**Comment by dgoldman-ebay** [comment]
No problem. :smile_cat:
