### ISSUE TITLE
NSRangeException

### ISSUE THREAD

**Issue by williamnoto** [card-io/card.io-iOS-SDK#143]
Anyone else experiencing this crash when compiling on Xcode 7, iOS9:

2015-09-28 08:32:48.843 heynay[1322:390922] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 7} out of bounds; string length 6'
*** First throw call stack:
(0x183350f5c 0x197f43f80 0x183350ea4 0x1833384e4 0x1832430d4 0x183338c90 0x10065e1b4 0x183289124 0x10065df00 0x10065eac4 0x10065ec6c 0x100632758 0x1888a762c 0x1888a71b0 0x188c3684c 0x188bf5750 0x188bf22b0 0x188b50844 0x188b5cde4 0x1888991e4 0x183307c30 0x1833059d4 0x183305e04 0x183234dc0 0x18e388088 0x18890ef60 0x1001350ec 0x19876e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

I'm using 5.0.3

**Comment by bluk** [comment]
Try the latest card.io Release `5.1.1` as of this comment. The issue was fixed in #120 but if you're experience it after upgrading to 5.1.1, please reopen.
