### ISSUE TITLE
iPad split-screen multitasking

### ISSUE THREAD

**Issue by jballer** [card-io/card.io-iOS-SDK#151]
In an application with multitasking enabled, `CardIOPaymentViewController` loses the video feed and reverts to a solid gray view whenever the application's window is not filling the screen.

**Comment by josharian** [comment]
Interesting! I wonder whether this is due to any of our UIWindow-related animation shenanigans. If you feel like investigating or experimenting, feel free to muck around: https://github.com/card-io/card.io-iOS-source.

**Comment by josharian** [comment]
I'm very unlikely to look at this, but @dgoldman-ebay might also find this interesting. (Or not.)

**Comment by jballer** [comment]
Thanks for the quick reply! I cloned the source and set up the environment as instructed, but haven't had a chance to dig in yet. I'll update here if/when I have time to dig in.

**Comment by dgoldman-ebay** [comment]
I do indeed find this interesting, but I don't really have time these days to pursue it. :crying_cat_face: 

When you split the screen, do we still have camera access? Or to put it another way, what if you split the screen prior to launching card.io's scanning view, and after arriving in multitasking mode you then launch card.io's scanner?

**Comment by jballer** [comment]
@dgoldman-ebay Sorry I was ambiguous about that… yes, we have camera access, and this occurs when splitting before app launch, while app running, and while the card.io view controller is presented.

If we switch back to full screen at any time, including while the card.io view controller is presented, it resumes normal behavior.

**Comment by josharian** [comment]
And under similar circumstances, does the Camera app continue to function normally?

**Comment by jballer** [comment]
That was the right question to ask. The built-in Camera app doesn't support split-screen…

**Comment by jballer** [comment]
The camera preview does work in the Messages app when you choose to take a photo, though will sometimes dismiss the camera controller on orientation/size change.

**Comment by josharian** [comment]
Hmmm. This sounds to me like something that is probably not fixable—or at least not worth trying to fix. Feel free to reopen if you disagree.
