### ISSUE TITLE
Followed all steps and still getting "Use of undeclared type 'CardIOPaymentViewControllerDelegate'" along with others

### ISSUE THREAD

**Issue by garronte** [card-io/card.io-iOS-SDK#152]
So i have followed every step and I still get issue with running on xcode 7. 

I have the 4 frameworks, linker flag, bridging header 

I can't figure out why it won't run
![screen shot 2015-10-19 at 12 47 52 pm](https://cloud.githubusercontent.com/assets/2533686/10584332/a2fe4764-765f-11e5-8a11-c0883fbf7070.png)

![screen shot 2015-10-19 at 12 46 40 pm](https://cloud.githubusercontent.com/assets/2533686/10584302/7abb9f54-765f-11e5-9b5a-02a63f6e9400.png)

**Comment by bluk** [comment]
Check if the Bridging header is configured (this should have happened automatically):
<img width="833" alt="screen shot 2015-10-19 at 1 29 55 pm" src="https://cloud.githubusercontent.com/assets/94150/10587227/cd1e2a9a-7665-11e5-9c07-6d80daaf9c58.png">

Also, is the `Link Binaries with Libraries` including the `libCardIO.a`?

<img width="808" alt="screen shot 2015-10-19 at 1 22 56 pm" src="https://cloud.githubusercontent.com/assets/94150/10586992/b5643f26-7664-11e5-9366-ab3d47d46ecb.png">

**Comment by garronte** [comment]
thanks
