### ISSUE TITLE
Library folder size is too large!

### ISSUE THREAD

**Issue by goktugaral** [card-io/card.io-iOS-SDK#155]
Hi there,

I was using early version of your library and it size was 13,8 MB. Recently, I updated my xCode and now I have iOS 9 support for my project. This is why I want to update my CardIO library and I did. 

But when I try to commit my project it takes too much time. Then I discovered the CardIO library size is 211,8 MB!!! Is it supposed to be like this? A bit too big for a library, don't you think? 

Thanks for your advice.

**Comment by bluk** [comment]
Hi, please see issue #147 specifically my comment [here](https://github.com/card-io/card.io-iOS-SDK/issues/147#issuecomment-149631466) for why the library is large. Your final app should not be large once the App Store compiles it. If you do not want to use Bitcode, you can get the source ( https://github.com/card-io/card.io-iOS-source ), disable Bitcode and re-build the project. It will return the size of the library to what it was once previously. Hope that helps explain.
