### ISSUE TITLE
Card Digits

### ISSUE THREAD

**Issue by rishigoel** [card-io/card.io-iOS-SDK#157]
If I wanted to change the API so that is was able to read a 9 digit bank account (I'm using a Manulife Bank card), where would I do so?  The format is 3 groups of 3

**Comment by dgoldman-ebay** [comment]
@rishigoel for the card scanner, this would be a very fundamental change, requiring a new neural-net model and many, many changes to the code.

**Comment by rishigoel** [comment]
so I'm assuming it would be very hard to do.  If I wanted to try, what file could I change?

**Comment by dgoldman-ebay** [comment]
This would touch several files in the [card.io-dmz repo](https://github.com/card-io/card.io-dmz) as well as a couple files in the [card.io-iOS-source repo](https://github.com/card-io/card.io-iOS-source). Also the [card.io-Android-source repo](https://github.com/card-io/card.io-Android-source), if to become an official change.
