### ISSUE TITLE
Identifying specific credit cards?

### ISSUE THREAD

**Issue by mitchellporter** [card-io/card.io-iOS-SDK#164]
When you add a credit card to Apple's wallet app (passbook), they don't just tell you whether it's Visa or Mastercard, they will show you an image of your actual credit card (not a screenshot).

How are they figuring out not only the brand of the card (Visa, Mastercard, Amex), but also the specific card? eg. Visa - Chase Slate card.

**Comment by dgoldman-ebay** [comment]
This information is expressed in some of the digits in the card number. See, for example, http://www.stevemorse.org/ssn/List_of_Bank_Identification_Numbers.html

**Comment by mitchellporter** [comment]
@dgoldman-ebay Thanks Dave
