### ISSUE TITLE
Is there any way how to suppress  _fauxCardLayer when using custom CardIOView? 

### ISSUE THREAD

**Issue by BrandU** [card-io/card.io-iOS-SDK#165]
Hi there, we are trying to implement our custom CardIOView with given design. Is there any way how we could disable that blurred layout in the center?

If not this could be enhancement.

**Comment by josharian** [comment]
I recommend grabbing the source code and modifying it. It should be fast and easy. I don't think it's worth adding an option to the API to disable it, but thanks for the suggestion.
