### ISSUE TITLE
Camera won't load after first scan

### ISSUE THREAD

**Issue by iurichiba** [card-io/card.io-iOS-SDK#169]
Hi!

I'm using CardIOView, and it works great (great job, btw), then I hide the view after it scans, using the data to fill my "virtual card" view. However, if I try to show the view again, the camera doesn't load. What should I do between scans? Should I reload the view?

Hope you guys can help me. Thanks!

**Comment by josharian** [comment]
They're one shot objects. Make a new one.

**Comment by dgoldman-ebay** [comment]
Hmm. If I recall, in our test app I included the case of showing/hiding a one-time-allocated `CardIOView`. Pretty sure that's supposed to work.

**Comment by iurichiba** [comment]
Any ideas on a workaround? I'm not instantiating mine programmatically, I'm using it w/ Interface Builder and manipulating it's constraints to hide/show.

If I were to create another instance of it I'd have to recreate it in the same place, recreate the constraints programmatically and set the outlets programmatically all over again.

I'll see if I can find a way to "clone" an object and it's constraints, but if it doesn't work I'll have to rewrite quite a chunk of my code.

Thanks for the answer, anyways :smile:

**Comment by dgoldman-ebay** [comment]
Yeah, see our instructions [here](https://github.com/card-io/card.io-iOS-SDK#option-2-include-a-hidden-cardioview-in-your-view).

**Comment by iurichiba** [comment]
@dgoldman-ebay I'll check the example. Maybe it's something to do with the height changing? I show it with the click of a button, and hide it after I get the answer.

However, I'm hiding/showing it by manipulating it's constraints to toggle between a fullscreen height and zero height, not by setting the hidden property.

**Comment by dgoldman-ebay** [comment]
Ah, that would explain the issue, I think. There's specific code in `setHidden:` that handles the magic.

Can you modify your code to set the `hidden` property?

**Comment by iurichiba** [comment]
@dgoldman-ebay sure, I'll try mixing it with setHidden, and if it doesn't work I'll just migrate it to a setHidden-only approach. Thanks for the help! :smile_cat:
