### ISSUE TITLE
Non convex bank card scanning, there is no good way to do it

### ISSUE THREAD

**Issue by AllLuckly** [card-io/card.io-iOS-SDK#170]
HI, card.io .
  Non convex bank card scanning, there is no good way to do it

**Comment by dgoldman-ebay** [comment]
By "convex" do you mean "embossed" (i.e., three-dimensional)?

If so, this is a known issue. See, for example, https://github.com/card-io/card.io-iOS-SDK/issues/20

We do not anticipate any improvements here in the near future, unfortunately.
