### ISSUE TITLE
Does this library work with iPhone 5C?

### ISSUE THREAD

**Issue by mixdesign** [card-io/card.io-iOS-SDK#171]
Some of my users cannot download my app from app store.
I'm just making a theory this could be the issue related with libraries Card IO is using which is not compatible with iPhone 5C architecture?!

What you think?

**Comment by bluk** [comment]
The library should work with iPhone 5C. The libraries are compiled for `armv7 armv7s arm64` architectures for the CocoaPods release. The armv7 code should be the same as running on any iPhone 5 and 4S as well. Is there a particular issue you were recalling?

**Comment by bluk** [comment]
Please comment back if this is an issue. Thanks.
