### ISSUE TITLE
Card expiry date is not getting scanned.

### ISSUE THREAD

**Issue by purvaDiaspark** [card-io/card.io-iOS-SDK#174]
On scanning credit card, it gives correct card number but unable to give expiry date. The proportion of getting successful expiry date is only 5%. I am not getting the exact reason of the same because, card number and expiry date both are embossed, the color combination on the card is all over same.

**Comment by bluk** [comment]
You can see https://github.com/card-io/card.io-iOS-SDK/issues/92 for a list of cards where the expiration date is scanned or not. If you can add the type of card you are having trouble with, this will help others understand what works and doesn't and will help any future work in this area.
