### ISSUE TITLE
Crash when the app is sent to background

### ISSUE THREAD

**Issue by awedeebawe** [card-io/card.io-iOS-SDK#176]
It happens rarely, but when I test my app and I open the scan view controller, if I tap the HOME button, and then resume the app, the app crashes.

I can't reproduce it in what cases this happens. But if someone has an idea how to fix, I'm opened for suggestions.

Best regards, L.

**Comment by bluk** [comment]
Is there any backtrace? What version of card.io are you using? Also, what devices? (Sorry for the 20 questions but some of these issues seem to be very specific to certain contexts, so it helps to have as much information as possible).

There was a fix in https://github.com/card-io/card.io-iOS-source/pull/43 for some screen hanging when the app is sent to the background for issue #153 . It was released in version 5.2.2.

**Comment by awedeebawe** [comment]
Yes, thank you. The latest version is ok.
