### ISSUE TITLE
how can i make the Scan full screen? 

### ISSUE THREAD

**Issue by farhansyed9** [card-io/card.io-iOS-SDK#180]
currently everything is working perfect. but im wondering how can i make the CardIOPaymentViewController scan full screen, currently theres two bars on the bottom and top on my iphone 6

**Comment by dgoldman-ebay** [comment]
Please see https://github.com/card-io/card.io-iOS-SDK/issues/116

**Comment by farhansyed9** [comment]
so what your saying is, theres no answer.

**Comment by dgoldman-ebay** [comment]
@farhansyed9 what I'm saying is that there is no "answer" possible. The aspect ratio of the camera's output (at the resolution our code depends on) differs from the aspect ratio of the screen.
