### ISSUE TITLE
Force landscape mode?

### ISSUE THREAD

**Issue by jeffblake** [card-io/card.io-iOS-SDK#183]
Hi,

I'm putting a `CardIOView` inside of a `UITableCellView`, which in turn is in a table view presented as a `FormSheet`

I'm setting a frame of 

        self.cardIOView.frame = CGRectMake(0, 0, self.view.frame.size.width, 400);

Which works perfectly when the iPad is in landscape mode. However, due to the camera view being 4:3, I cannot make it look good in portrait mode - there are bars on the left and right that the camera is not occupying. I want it to be full width in both portrait and landscape with a height of about 250-400.

If I could force the card io view to show its landscape form, then I think it would work. Possible?

**Comment by dgoldman-ebay** [comment]
So your idea is to have the iPad in portrait orientation, but the CardIOView in landscape?

No, I don't think that will work. The camera feed would still be portrait, and that's what the CardIOView displays.

Might it work if you gave the CardOIView the width of your cell, but a height that is 4/3 of that? And then clip the CardIOView to the cell's `contentView`?

**Comment by jeffblake** [comment]
I got that working! Thanks for the tip. It's a little janky... I have to set a negative origin as well in order to center the aimer frame.
 One other question, if you don't mind, the CardIO view seems to be intercepting touches on the cell. The only way I can trigger a `didSelectRowAtIndexPath` is to tap the CardIO view with 2 fingers. Strange... any ideas on that? I've tried adding a `UITapGuestureRecognizer` on the cell, cardio view, etc and no luck (I think the tableview intercepts those). I want to be able to toggle the CardIO view on tap.

**Comment by dgoldman-ebay** [comment]
@jeffblake glad that's mostly working for you.

The CardIOView does indeed have its own `UITapGestureRecognizer`, to allow the user to force the camera to re-autofocus. If you really do want to take that ability away from your users, you could add your own transparent view in front of the CardIOView and capture taps there.

**Comment by jeffblake** [comment]
Got it. Thanks.

**Comment by dgoldman-ebay** [comment]
:)
