### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by robfierro** [card-io/card.io-iOS-SDK#184]
It would be nice to make this compatible with Carthage

**Comment by bluk** [comment]
Please see if https://github.com/card-io/card.io-iOS-source#if-you-use-carthage-then-add-this-line-to-your-cartfile meets your needs. Thanks!

**Comment by bluk** [comment]
If you have other questions or if the initial Carthage support isn't working, please leave a comment. Thanks.

**Comment by robfierro** [comment]
That works :) Thanks!
