### ISSUE TITLE
Issue Facing in SearchBar(if i am typing Four characters in searcher showing Error)

### ISSUE THREAD

**Issue by SusheelYadavAhex** [card-io/card.io-iOS-SDK#189]
*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 4} out of bounds; string length 3'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110856e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010fea9deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110856d9d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00000001108425aa -[NSTaggedPointerString getCharacters:range:] + 394
	4   CoreFoundation                      0x000000011072f8ca CFStringCompareWithOptionsAndLocale + 2970
	5   CoreFoundation                      0x0000000110842f0b -[NSTaggedPointerString compare:options:range:locale:] + 219
	6   Foundation                          0x000000010fa40e37 -[NSString compare:options:range:] + 29
	7   FindYourNeed                        0x000000010daa2989 -[PlaceTypeViewController searchTableList] + 649
	8   FindYourNeed                        0x000000010daa248d -[PlaceTypeViewController searchBar:textDidChange:] + 205
	9   UIKit                               0x0000000111a28c6f -[UISearchBar(UISearchBarStatic) _searchFieldEditingChanged] + 144
	10  UIKit                               0x0000000111638194 -[UIApplication sendAction:to:from:forEvent:] + 92
	11  UIKit                               0x00000001117a76fc -[UIControl sendAction:to:forEvent:] + 67
	12  UIKit                               0x00000001117a79c8 -[UIControl _sendActionsForEvents:withEvent:] + 311
	13  UIKit                               0x000000011201ba85 -[UITextField fieldEditorDidChange:] + 206
	14  UIKit                               0x0000000112026cb7 -[UITextInputController _sendDelegateChangeNotificationsForText:selection:] + 138
	15  UIKit                               0x0000000112029281 -[UITextInputController _insertText:fromKeyboard:] + 893
	16  UIKit                               0x0000000112029bcd -[UITextInputController insertText:] + 365
	17  UIKit                               0x00000001117b3728 -[UIFieldEditor insertFilteredText:] + 800
	18  UIKit                               0x00000001120207d7 -[UITextField insertFilteredText:] + 103
	19  UIKit                               0x00000001118dea83 -[UIKeyboardImpl insertText:] + 125
	20  UIKit                               0x00000001118db278 -[UIKeyboardImpl performKeyboardOutput:] + 496
	21  UIKit                               0x00000001118dae65 __55-[UIKeyboardImpl handleKeyboardInput:executionContext:]_block_invoke_2 + 164
	22  UIKit                               0x0000000112049724 -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 332
	23  Foundation                          0x000000010fa92067 __NSThreadPerformPerform + 283
	24  CoreFoundation                      0x0000000110782a31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x000000011077895c __CFRunLoopDoSources0 + 556
	26  CoreFoundation                      0x0000000110777e13 __CFRunLoopRun + 867
	27  CoreFoundation                      0x0000000110777828 CFRunLoopRunSpecific + 488
	28  GraphicsServices                    0x0000000113d96ad2 GSEventRunModal + 161
	29  UIKit                               0x0000000111636610 UIApplicationMain + 171
	30  FindYourNeed                        0x000000010daaba3f main + 111
	31  libdyld.dylib                       0x0000000112cb192d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by SusheelYadavAhex** [comment]
[FindYourNeed.xcodeproj.zip](https://github.com/card-io/card.io-iOS-SDK/files/152293/FindYourNeed.xcodeproj.zip)

**Comment by dgoldman-ebay** [comment]
@SusheelYadavAhex it looks like you have posted to a repo that's not the one you intended.
