### ISSUE TITLE
How to adjust the width and height of scan area (i.e. green bracket) pragmatically

### ISSUE THREAD

**Issue by surendherCES** [card-io/card.io-iOS-SDK#191]
I am trying to modify the size of scannable area. 

Please do let me know how it can be done.

**Comment by bluk** [comment]
While you can modify the [camera view](https://github.com/card-io/card.io-iOS-source/blob/master/Classes/CardIOCameraView.mm) and the [green bracket](https://github.com/card-io/card.io-iOS-source/blob/master/Classes/CardIOGuideLayer.mm) if you want to compile the library from source, this won't really work without more complicated changes to how card.io reads and understands the scanned images itself.
