### ISSUE TITLE
Is scanning a printed card / image possible? 

### ISSUE THREAD

**Issue by freak4pc** [card-io/card.io-iOS-SDK#196]
I'm working on an app that scans credit cards and it seems impossible to use a printed stub/mock card on a piece of paper... I thought it would be better than using my actual credit card for testing. 

Is there anything specific to the printed image use case that would prevent it from being recognised as a credit card?

This is what I mean ... you could call it test cases :) 
![image](https://cloud.githubusercontent.com/assets/605076/14587679/852f7a66-04bf-11e6-9803-c66a2a815d60.png)

**Comment by bluk** [comment]
The models for image recognition are based on embossed credit card digits on a card. I don't think it will be able to pick up the printed card numbers on paper unfortunately.
