### ISSUE TITLE
Done/Cancel Button after scanning the card are hidden

### ISSUE THREAD

**Issue by lupugabriel** [card-io/card.io-iOS-SDK#197]
After i scan the card succesfully Cancel Button and Done Button cannot be seen. 
The buttons works trigging the delegates but i can't see them. 
Same happens if i try to manually add the card.

Thanks

**Comment by bluk** [comment]
Can you tell what device and version of iOS you are using? Also, a screenshot may be helpful. Thanks.

**Comment by mwoollard** [comment]
I've just done initial integration of card.io + Braintree Drop In SDK and have hit the same issue. Once card scan completed I get a screen with the card image + card number overwritten (blocked out in attached). No buttons to continue and need to terminate the app.

![img_5191](https://cloud.githubusercontent.com/assets/150681/25431152/4cd0a918-2a77-11e7-9042-482858356c85.png)

Am using pre-built binaries of your SDK version 5.4.1 on iOS 10.3.1 (14E304) on iPhone 7. I've looked over the Braintree source and it just opens your view controller and waits for a delegate callback that never comes so don't see the issue their side. One thought, this is all built into a framework within our app as opposed to the main app bundle incase relevant. 

Thanks
Mark

**Comment by mwoollard** [comment]
Further info, I've done some debugging and figured out that in my case the buttons are there but just tinted white (since this is the tint colour of UIBarButtonItems in the parent app). It appears that the dialog is honouring the appearance proxy for the button and title text but not for the bar itself. In our app delegate:

```
    UIColor *primaryColor = [UIColor themePrimaryColor];
    UIColor *complementColor = [UIColor themePrimaryColorCompliment];
    [[UINavigationBar appearance] setTitleTextAttributes:@{NSForegroundColorAttributeName: complementColor}];
    [[UINavigationBar appearance] setBarTintColor:primaryColor];
    [[UINavigationBar appearance] setTranslucent:NO];
    [[UINavigationBar appearance] setTintColor:complementColor];
    [[UIBarButtonItem appearance] setTintColor:complementColor];
    [[UIBarButtonItem appearance] setTitleTextAttributes:@{NSForegroundColorAttributeName:complementColor} forState:UIControlStateNormal];
```
Can card.io be themed? Or if not can you fix so it removes any host app styling?

**Comment by sdcoffey** [comment]
Hey @mwoollard,

Thanks for reporting this. This is actually a [Drop-in issue](https://github.com/braintree/braintree-ios-drop-in/issues/41). I've opened a new issue there and tagged you on it. We'll keep you posted as a fix goes out for this. 


**cc**: @bluk looks like I'm not a contributor on this repository, would you mind closing this?

**Comment by josharian** [comment]
Or better, @bluk , make @sdcoffey  a contributor. :)

**Comment by bluk** [comment]
Yup, done. :)
