### ISSUE TITLE
React-native & Card.io

### ISSUE THREAD

**Issue by steevivo** [card-io/card.io-iOS-SDK#206]
HI,

Have you planned use with React-native IOS and Android   ? 

Thanks

**Comment by jaypatel512** [comment]
Hey @steevivo !

We made our first public repository https://github.com/card-io/react-native-card-io for react-native-card-io. We are making some good progress on android, however, we still need ios implementation on it. Feel free to checkout the plugin, and if possible, help us with the iOS implementation.

I am closing this issue for now.
