### ISSUE TITLE
SDK is crashing for the iOS 10 beta 

### ISSUE THREAD

**Issue by Venkata-Maniteja** [card-io/card.io-iOS-SDK#209]
My app is unable to open the camera and it crashes right way when I try to present the scan view controller. I'm using the same way mentioned in the documents of card.io. This way works fine on previous versions of iOS but not in iOS 10. Strange thing is that there is no crash log for the crash.

**Comment by bluk** [comment]
@Venkata-Maniteja Can you check to make sure you have a usage description in your Info.plist for NSCameraUsageDescription? This seems to be part of the new iOS Security Features. Apps built with the iOS 9 SDK (and not rebuilt with iOS 10/Xcode 8-beta) will be fine. However, if you do use the iOS 10 SDK, you will need to add a [`NSCameraUsageDescription`](https://developer.apple.com/library/prerelease/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW15) to your `Info.plist`. This string describes why you need access to the camera. You may have other permissions where you need to add usage descriptions, but I believe card.io should only require the camera.

See [What's New in iOS](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewIniOS/Articles/iOS10.html) under the last bullet of Security and Privacy Enhancements. [WWDC 2016 Session 709](https://developer.apple.com/videos/play/wwdc2016/709/) also has more info.

**Comment by Venkata-Maniteja** [comment]
Adding the description worked. Hence closing the issue.
