### ISSUE TITLE
Since bitcode has been enabled in 5.2 I have transitive dependency issues

### ISSUE THREAD

**Issue by sergiofraile** [card-io/card.io-iOS-SDK#213]
Since bitcode has been enabled in 5.2.0, as CardIO is a dependency of my own pod, I have a transitive dependency error when running pod install/update. I had to roll back to 5.1.0.

This is the Podspec I'm using

```
Pod::Spec.new do |s|
  s.name             = 'MyPod'
  s.version          = '0.1.0'


  s.ios.deployment_target = '9.0'
  s.platform     = :ios, '9.0'

  s.source_files = 'MyPod/Classes/**/*'

  s.resources = ["MyPod/Resources/*.storyboard"]

  s.resource_bundles = { 'MyPod' => ['MyPod/Assets/*.png', 'MyPod/Classes/**/*.xib'] }

  s.pod_target_xcconfig = {
    'OTHER_SWIFT_FLAGS[config=Debug]' => '-D DEBUG'
  }

  s.public_header_files = 'Pod/Classes/**/*.h'
  s.frameworks = 'UIKit', 'Foundation', 'QuartzCore'
  s.dependency 'SDWebImage', '~> 3.7.6'
  s.dependency 'BEMCheckBox', '~> 1.2.1'
  s.dependency 'Alamofire', '~> 3.4.0'
  s.dependency 'SwiftyJSON', '~> 2.3.2'
  s.dependency 'CardIO', '= 5.1.0'
  s.dependency 'SHSPhoneComponent', '~> 2.15'

end
```

**Comment by bluk** [comment]
Reproduced this issue, but couldn't find a way to get around this. Seems like a CocoaPods issue.

I saw you [found a workaround](https://github.com/CocoaPods/CocoaPods/issues/3267#issuecomment-234897502) by [disabling the check](https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-84005488), so will close this issue. However, if someone else has any fixes that can be made to card.io, please issue a PR or leave a comment. Thanks.
