### ISSUE TITLE
Card.Io iOS sdk scan usersname

### ISSUE THREAD

**Issue by flexmcpee** [card-io/card.io-iOS-SDK#225]
I am using the CardIOView and CardIOViewDelegate classes and there is no BOOL that I can set to YES for scanning collectCardholderName. I can see it is available in the CardIOPaymentViewController however I am not using those view controller classes.

I am declaring CardIOView like below.

`@property(nonatomic, strong, readwrite) IBOutlet CardIOView *cardIOViewer;`
and accessing and setting its properties like below in viewDidLoad.

```
self.cardIOViewer.hideCardIOLogo = YES;
self.cardIOViewer.scanExpiry = YES
```;
I want to be able to scan the users name also ie below as the documentation says the default is false however that property isn't available?

`self.cardIOViewer.collectCardholderName = YES`

**Comment by lkorth** [comment]
card.io does not scan card holder names, see #111. `collectCardholderName` is an option to prompt the user to input their name.

**Comment by flexmcpee** [comment]
Ah ok I found the docs slightly confusing. No probs and thanks.
