### ISSUE TITLE
linker warning when building with XCode8.0 or greater

### ISSUE THREAD

**Issue by jaz-ah** [card-io/card.io-iOS-SDK#229]
- CardIO (5.4.1)  (using cocoapods)
- Xcode version: 8.0, 8.1 or 8.2 (Beta)
- iOS or Simulator: 10.0 / 10.1 / 10.2 simulator
- iOS Version: 10.0 / 10.1 / 10.2 simulator
- Swift version: 3.0

Steps to Reproduce:

1.  Just build an application with the cardio sdk using cocoapods with the above versions, will get the linker warning:
ld: warning: Some object files have incompatible Objective-C category definitions. Some category metadata may be lost. All files containing Objective-C categories should be built using the same compiler.

I have broken this down and limited it to a test application with just the cardio sdk.  It looks like the cardio sdk is probably built w/ XCode7.x and we are getting this compatibility warning.

**Comment by jaz-ah** [comment]
@bluk any update on this one - could you possibly rebuild the sdk with the latest Xcode to help us get rid of this warning?  Thanks.

**Comment by tomaskraina** [comment]
Any update?

**Comment by chrismanderson** [comment]
Sorry to add another comment, but any way we can get this updated? Been seeing this warning for so long now and I'd love to be rid of it.

**Comment by jaz-ah** [comment]
@chrismanderson looks like this is a dead project - good news is I updated to Swift4/XCode9 and the warning went away...

**Comment by chrismanderson** [comment]
Ah interesting; I'm on Xcode 9 but not Swift 4 yet. I'll give that a try. Cheers!

**Comment by jaz-ah** [comment]
np - yeah moving to Xcode9 didn't do it for me either, it was the Swift4 conversion.  good luck, it was pretty straightforward.

**Comment by staminajim** [comment]
Hi all, sorry to revive an old thread, but was wondering if anyone has had any luck with Xcode 9.3 + Swift 4.1?

Including the CardIO pod results in the wonderful `ld: warning: Some object files have incompatible Objective-C category definitions. Some category metadata may be lost. All files containing Objective-C categories should be built using the same compiler.` warning again.
