### ISSUE TITLE
Save scanned Image

### ISSUE THREAD

**Issue by shamilasallay** [card-io/card.io-iOS-SDK#242]
I use card.io to scan cards in an IOS app. I want to save them in the firebase storage, but I cannot find a way to retrieve the captured image. Is there a way to that or is it impossible in card.io in IOS? There is EXTRA_RETURN_CARD_IMAGE for Android but what will be it's IOS conversion?

**Comment by josharian** [comment]
Take a look at the header files. It is there. However, storing credit card images anywhere is seriously inadvisable. And for those credit cards (mostly AmEx) that have the CVV printed on the front, storing it is a PCI violation. The ability to get the scanned card image was added for those using card.io for other cards (e.g. insurance cards), not for credit cards.
