### ISSUE TITLE
Done button disable in American Card. why?

### ISSUE THREAD

**Issue by Bhadresh4488** [card-io/card.io-iOS-SDK#257]
I am scan american credit card that it is 15 digit card number. scan is good working but done button can't enable.

### General information

* SDK/Library version: 
* iOS Version and Device: 
* Integration type and version:

**Comment by FreddyRodrigoPoot** [comment]
Did you verify that you input 4 digits in the cv field

**Comment by Bhadresh4488** [comment]
Thanks,
I enter cv 3 digit that it's issue coming after your comment check & enter cvv2(AmEx's) 4 digit that display done button
