### ISSUE TITLE
Does Card.io iOS or Android SDK used in an app gets the app into PCI scope? Can Card.io be out of PCI scope for the app?

### ISSUE THREAD

**Issue by pramod-rao** [card-io/card.io-iOS-SDK#278]
### General information

* SDK/Library version: 
* iOS Version and Device: 
* Integration type and version:

**Comment by crookedneighbor** [comment]
The self-contained nature of a mobile app means that PCI compliance is different than it would be on a website. A mobile app using card.io is SAQ-A compliant.

**Comment by pramod-rao** [comment]
Thanks for the quick response
