### ISSUE TITLE
Changing Cancel and Done button colors 

### ISSUE THREAD

**Issue by henrythe9th** [card-io/card.io-iOS-SDK#61]
Dear CardIO,

Is there a way to change the colors of the "Cancel" and "Done" buttons on the Navbar for the CardIOPaymentViewController?

I noticed the keepStatusBarStyle property and it was very helpful in keeping the style of our NavBar.

Thanks!

**Comment by NasirMalik** [comment]
Nothing worked but this. Took almost two hours to figure-out. 

```
NSDictionary *attributes = [NSDictionary dictionaryWithObjectsAndKeys:
                                [UIColor redColor],UITextAttributeTextColor,
                                nil];
    [[UIBarButtonItem appearanceWhenContainedIn:[UINavigationBar class], nil]
     setTitleTextAttributes:attributes
     forState:UIControlStateNormal];
```

**Comment by alexandermcpherson** [comment]
Swift implementation.

`cardIOVC?.navigationBar.titleTextAttributes = [NSForegroundColorAttributeName : UIColor.white, NSFontAttributeName : UIFont(name: "AvenirNext-Regular", size: 16)!]
        UIBarButtonItem.appearance(whenContainedInInstancesOf: [CardIOPaymentViewController.self]).setTitleTextAttributes([NSForegroundColorAttributeName : UIColor.white, NSFontAttributeName : UIFont(name: "AvenirNext-Regular", size: 16)!], for: .normal)
`
Adjust font and color of the nav bar and the nav buttons to your needs. All shown for full customisation.
