### ISSUE TITLE
Property 'appToken' not found on object of type 'CardIOPaymentViewController *'

### ISSUE THREAD

**Issue by onmyway133** [card-io/card.io-iOS-SDK#72]
I see that 3.10.0 removes this property. So this property is useless?

**Comment by gaharrington** [comment]
I am upgrading an old app. 

What is the replacement for appToken...I can't seem to find any info on this.

**Comment by josharian** [comment]
There is no replacement; app tokens are not needed. Simply delete the line of code where you were setting it.
