### ISSUE TITLE
Manual input labels glitch in right-to-left languages

### ISSUE THREAD

**Issue by danieltskv** [card-io/card.io-iOS-SDK#90]
I'm working on an app with Hebrew support, and Card.IO's manual input view controller has some UILabels out of place (the right screen edge). I think it's some kind of a layout issue.

![screen shot 2015-01-09 at 21 44 37](https://cloud.githubusercontent.com/assets/8099541/5686231/f2fae7b2-9849-11e4-9a99-c2e15dbf9603.png)

P.S.
The layout is different for RTL languages, It has three rows instead of two. Is that intentional?

**Comment by dgoldman-ebay** [comment]
Thanks for bringing this to our attention, @danieltskv. We'll see if we can reproduce this.

> The layout is different for RTL languages, It has three rows instead of two. Is that intentional?

Actually, the layout is different not for RTL languages, but is based on whether the labels for each field would fit into the 2-row format. In this case, the string for "postal code" is too long to fit.

However, in [the current version of card.io](https://github.com/card-io/card.io-iOS-SDK/releases), that string is shorter than the one appearing in your screenshot. What version of card.io are you using?

**Comment by dgoldman-ebay** [comment]
@danieltskv I've edited my original response regarding the version of card.io involved. Sorry -- I was looking at the wrong string in our resources.

**Comment by dgoldman-ebay** [comment]
Yup, I can reproduce this issue. Things were fine in iOS 7, but apparently layout in iOS 8 is slightly different.

A fix will be coming soon.

**Comment by danieltskv** [comment]
@dgoldman-ebay Great! I haven't finished writing a response and you already managed to check things out.
Cheers!

**Comment by dgoldman-ebay** [comment]
@danieltskv It's a bit late in the day on a Friday for me to push out a card.io release. Probably this fix will get released on Tuesday (Jan 13).

**Comment by danieltskv** [comment]
@dgoldman-ebay It's totally fine. thank you for the fix!

**Comment by dgoldman-ebay** [comment]
Forgot to post here earlier today! This issue has indeed now been fixed. And I improved the two-rows vs. three-rows situation while I was there. https://github.com/card-io/card.io-iOS-SDK/releases
