### ISSUE TITLE
xcode6 arm64 link error(card-3.io-iOS-SDK-master 5.0.0 (Tue 1/20/2015))

### ISSUE THREAD

**Issue by lyt3251** [card-io/card.io-iOS-SDK#93]
I need your help. I can't use the  latest  versions. Thanks

Undefined symbols for architecture arm64:
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      scanner_add_frame_with_expiry(ScannerState*, _IplImage*, bool, FrameScanResult*) in libCardIO.a(libCardIO.a-arm64-master.o)
      find_character_groups_for_stripe(_IplImage*, _IplImage*, int, long, std::__1::vector<GroupedRects, std::__1::allocator<GroupedRects> >&, std::__1::vector<GroupedRects, std::__1::allocator<GroupedRects> >&) in libCardIO.a(libCardIO.a-arm64-master.o)
      std::__1::enable_if<(__is_forward_iterator<GroupedRects*>::value) && (is_constructible<GroupedRects, std::__1::iterator_traits<GroupedRects*>::reference>::value), void>::type std::__1::vector<GroupedRects, std::__1::allocator<GroupedRects> >::assign<GroupedRects*>(GroupedRects*, GroupedRects*) in libCardIO.a(libCardIO.a-arm64-master.o)
      std::__1::vector<GroupedRects, std::__1::allocator<GroupedRects> >::allocate(unsigned long) in libCardIO.a(libCardIO.a-arm64-master.o)
      std::__1::vector<CharacterRect, std::__1::allocator<CharacterRect> >::allocate(unsigned long) in libCardIO.a(libCardIO.a-arm64-master.o)
      std::__1::enable_if<(__is_forward_iterator<CharacterRect*>::value) && (is_constructible<CharacterRect, std::__1::iterator_traits<CharacterRect*>::reference>::value), void>::type std::__1::vector<CharacterRect, std::__1::allocator<CharacterRect> >::assign<CharacterRect*>(CharacterRect*, CharacterRect*) in libCardIO.a(libCardIO.a-arm64-master.o)
      void std::__1::vector<GroupedRects, std::__1::allocator<GroupedRects> >::__push_back_slow_path<GroupedRects const>(GroupedRects const&) in libCardIO.a(libCardIO.a-arm64-master.o)
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      cv::Exception::Exception(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::error(cv::Exception const&) in libCardIO.a(libCardIO.a-arm64-master.o)
      ScanFrameAnalytics::operator=(ScanFrameAnalytics const&) in libCardIO.a(libCardIO.a-arm64-master.o)
      std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::__construct_node(std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) in libCardIO.a(libCardIO.a-arm64-master.o)
      ScanFrameAnalytics::ScanFrameAnalytics(ScanFrameAnalytics const&) in libCardIO.a(libCardIO.a-arm64-master.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      categorize_expiry_digits(_IplImage*, _IplImage*, GroupedRects, char*) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::Exception::formatMessage() in libCardIO.a(libCardIO.a-arm64-master.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      best_line_for_sample(_IplImage*, unsigned char) in libCardIO.a(libCardIO.a-arm64-master.o)
      categorize_expiry_digits(_IplImage*, _IplImage*, GroupedRects, char*) in libCardIO.a(libCardIO.a-arm64-master.o)
      llcv_equalize_hist(_IplImage const*, _IplImage*) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::fastMalloc(unsigned long) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::convertAndUnrollScalar(cv::Mat const&, int, unsigned char*, unsigned long) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::binary_op(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, void (* const*)(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char*, unsigned long, cv::Size_<int>, void*), bool) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::arithm_op(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, int, void (**)(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char*, unsigned long, cv::Size_<int>, void*), bool, void*) in libCardIO.a(libCardIO.a-arm64-master.o)
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      best_line_for_sample(_IplImage*, unsigned char) in libCardIO.a(libCardIO.a-arm64-master.o)
      categorize_expiry_digits(_IplImage*, _IplImage*, GroupedRects, char*) in libCardIO.a(libCardIO.a-arm64-master.o)
      llcv_equalize_hist(_IplImage const*, _IplImage*) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::fastMalloc(unsigned long) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::convertAndUnrollScalar(cv::Mat const&, int, unsigned char*, unsigned long) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::binary_op(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, void (* const*)(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char*, unsigned long, cv::Size_<int>, void*), bool) in libCardIO.a(libCardIO.a-arm64-master.o)
      cv::arithm_op(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, int, void (**)(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char*, unsigned long, cv::Size_<int>, void*), bool, void*) in libCardIO.a(libCardIO.a-arm64-master.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dgoldman-ebay** [comment]
@lyt3251 please double-check that you have followed this [step of our Setup instructions](https://github.com/card-io/card.io-iOS-SDK#setup):

> In your project's Build Settings (in the `TARGETS` section, not the `PROJECTS` section), add `-lc++` to `Other Linker Flags`.

**Comment by mitchellporter** [comment]
@dgoldman-ebay Just a quick question, for `Other Linker Flags`, there are both `Debug` and `Release options`, do we add `-lc++` to both of those?

**Comment by dgoldman-ebay** [comment]
@mitchellporter yes, to both. (If you don't click the disclosure triangle to reveal the separate settings for `Debug` and `Release`, you can edit both at once.)

**Comment by mitchellporter** [comment]
@dgoldman-ebay Thanks Dave
