### ISSUE TITLE
Stutter in animation when dismissing from cancel button

### ISSUE THREAD

**Issue by wattson12** [card-io/card.io-iOS-SDK#97]
Because the camera overlay view is still running when the CardIOPaymentViewController is dismissed from the cancel button, there is a delay during animation (it moves about the height of the nav bar, pauses and then continues). There is no delay when dismissing from the done button after scanning is complete

The fix I have is to get access to the `cardIOView` property of `cardIOViewController`, and call `stopSession` before dismissing the view controller (category method I am using below).

Obviously using these private methods is not the nicest way of doing things so is there a better alternative to fixing this issue?

```ObjectiveC
- (void)ttn_stopScanningSession
{
    UIViewController *cardIOViewController = self.topViewController;

    if ([cardIOViewController respondsToSelector:@selector(cardIOView)])
    {
        NSObject *cardIOView = [cardIOViewController cardIOView];
        
        if ([cardIOView respondsToSelector:@selector(stopSession)])
        {
            [cardIOView stopSession];
        }
    }
}
```

**Comment by dgoldman-ebay** [comment]
@wattson12 there's a stutter we're aware of that we never found a solution for. If this is that same stutter, and your fix is all we need to solve it, that would be great!

When I get a chance, I'll see how your fix works when integrated into our code. (Or else you can try for yourself in [card.io-iOS-source](https://github.com/card-io/card.io-iOS-source) and send us a Pull Request!)

If it works for me, then you'll see a relevant mention in the card.io-iOS-SDK release notes. Until then, you should be safe to continue using your category.

**Comment by dgoldman-ebay** [comment]
Ah. Different stutter. None of us had previously noticed this one that you're reporting, but now that I look I see what you mean.

I'll try to incorporate your fix in the coming week or so.

**Comment by wattson12** [comment]
Great, thanks for this. Also I only realised there was an open source repo after submitting this, I'll make a proper pull request if I have any new issues.

**Comment by dgoldman-ebay** [comment]
@wattson12 sounds great!

(Though please don't feel obliged to understand our somewhat convoluted code well enough to actually create a PR whenever you run into a problem.)

Hey -- so if you weren't aware of our open source repo, how did you figure out your fix?

**Comment by wattson12** [comment]
I used the objc runtime to dump a list of class methods, and took a few educated guesses. Thanks for the well named methods :+1:

**Comment by dgoldman-ebay** [comment]
Well done!

**Comment by dgoldman-ebay** [comment]
Now officially [released](https://github.com/card-io/card.io-iOS-SDK/releases).

**Comment by wattson12** [comment]
Awesome, thanks for the quick fix
